### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'specifier'

### ISSUE THREAD

**Issue by elcolie** [pyenv/pyenv#1013]
vphilippon could not be able to reproduce my issue on his Linux, but I do both on OSX and Debian
https://github.com/jazzband/pip-tools/issues/576

OSX is not in my hand. I will show Debian Stretch because it raises same error.

```bash
(soken-web) sarit@sniper:~/Code/soken/soken-web$ uname -a
Linux sniper 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
(soken-web) sarit@sniper:~/Code/soken/soken-web$ python -V
Python 3.6.2
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip --version
pip 9.0.1 from /home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages (python 3.6)
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip-compile --version
pip-compile, version 1.10.1
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pip-compile 
Traceback (most recent call last):
  File "/home/sarit/.pyenv/versions/soken-web/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/scripts/compile.py", line 136, in cli
    for ireq in ireqs
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/scripts/compile.py", line 137, in <dictcomp>
    if is_pinned_requirement(ireq) and key_from_req(ireq.req) not in upgrade_pkgs_key}
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/piptools/utils.py", line 121, in is_pinned_requirement
    if len(ireq.specifier._specs) != 1:
  File "/home/sarit/.pyenv/versions/3.6.2/envs/soken-web/lib/python3.6/site-packages/pip/req/req_install.py", line 287, in specifier
    return self.req.specifier
AttributeError: 'NoneType' object has no attribute 'specifier'
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pyenv -V
pyenv: no such command `-V'
(soken-web) sarit@sniper:~/Code/soken/soken-web$ pyenv --version
pyenv 1.1.3-51-gaf8cca9
```

**Comment by yyuu** [comment]
Why you thought this is a pyenv error?

**Comment by elcolie** [comment]
My bad. It fixed now. Your comment made me reproduce again in new computer and it has no problem.
