### ISSUE TITLE
[pipenv] locale not supported

### ISSUE THREAD

**Issue by wvxvw** [pyenv/pyenv#1030]
Hello.

Right after installing `pipenv` through `pip3` installed with Ubuntu's package manager and attempting to create a virtual environment I've got this:

```
$ pipenv --three
Creating a virtualenv for this project…
Using /usr/bin/python3 to create virtualenv…
⠋Traceback (most recent call last):
  File "/usr/local/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/usr/local/lib/python3.5/dist-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/lib/python3.5/dist-packages/pew/pew.py", line 42, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.5/dist-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/lib/python3.5/locale.py", line 577, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_IL

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1728, in cli
    ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 630, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 334, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 388, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```
I don't know what do you need my locale for, but, apparently, this isn't a supported one.  And, this error renders all future use of `pipenv` impossible.

If locale `en_IL` sounds unfamiliar, it is because it is new...  It was added very recently: https://sourceware.org/git/gitweb.cgi?p=glibc.git;h=146ffc146fe3bf97cd3bc1a649f1ffa8acfa4a0d

I can imagine this to be more of Python's problem since its newest and shiniest "everything is Unicode" attitude doesn't really work...  But, to keep things practical, you shouldn't probably assume that you know what locales are there, or, at least use some default, if faced with unfamiliar one.

My operating system details:

```
$ uname -a
Linux linux-il-wvxvw 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release 
No LSB modules are available.
```
(it's Ubuntu 17)

```
$ dpkg -s python3-pip | grep Version:
Version: 9.0.1-2
```

```
$ python --version
Python 2.7.13
```

```
$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

**Comment by wvxvw** [comment]
Oh, I'm really sorry! Now I see it's a wrong project! My blind clicking through Google search results :(
