### ISSUE TITLE
MAC OS 10.13.1 + pyenv 1.1.5 + Python 3.6.3 : Attempting to use requests api resulting ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) in 

### ISSUE THREAD

**Issue by ramukarnati** [pyenv/pyenv#1039]
Mac with  High Sierra (10.13.1) and with the pyenv (1.1.5) Attempting to use requests api resulting ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) in 

On a different with using system installed python, it works fine. Below are more details.

```
Python 3.6.3 (default, Oct 19 2017, 16:29:35)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
>>> import urllib3
>>> http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
>>> http.request('GET', '<any url>')
Traceback (most recent call last):
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/rkarnati/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<url>', port=443): Max retries exceeded with url: /api/version (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
>>>
```

**Comment by leeleeee** [comment]
I also have this issue with macOS Sierra 10.12.6, pyenv 1.1.5 and Python 3.6.1. I think this is caused by there are many openssl versions. 
I just use the openssl installed by brew to replace the system openssl, then it seems ok now.

**Comment by cornfeedhobo** [comment]
Same here. OpenSuse 42.3, pyenv 1.2.1, target python 2.7.14.
I have read the [common issues(https://github.com/pyenv/pyenv/wiki/Common-build-problems) wiki entry, and ensured that dependencies are installed.
Verbose builds don't not print any error related to ssl either. Just this error once a request is made.

**Comment by native-api** [comment]
This means that something is wrong with certificates in question and/or the certificate store of the OpenSSL being used (whatever it is).
Without this info, impossible to say anything.
