### ISSUE TITLE
pipenv install --dev '-e . '  -->  TypeError: stat: path should be string

### ISSUE THREAD

**Issue by y2kbugger** [pyenv/pyenv#1043]
https://docs.pipenv.org/basics.html

Following instructions here for Editable Dependencies to add the source folder package to the site-packages in editable mode.

I want users to be able to run

    $ pipenv install --dev
    $ pipenv run pytest

and then be able to make a change to the repo and run

    $ pipenv run pytest

again to evaluate a effect of the changes.

Is `pipenv install --dev '-e . '` not the right tool for the job? or is this actually broken?

```
$ pipenv install --dev '-e . '
Installing -e . …
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/usr/lib/python3.6/site-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

```
$ pipenv run python --version
Python 3.6.2
$ pipenv --version
pipenv, version 8.3.2


```

**Comment by yyuu** [comment]
Can’t you read the repo name? :-1:
