### ISSUE TITLE
OSX use pyinstaller Error

### ISSUE THREAD

**Issue by HoneyPig** [pyenv/pyenv#1095]
``` 
76 INFO: PyInstaller: 3.3.1
76 INFO: Python: 3.6.0
95 INFO: Platform: Darwin-17.4.0-x86_64-i386-64bit
97 INFO: wrote /Users/chenzhi/MyGitlab/python-tools/pyQrcode.spec
100 INFO: UPX is not available.
102 INFO: Extending PYTHONPATH with paths
['/Users/chenzhi/MyGitlab/python-tools', '/Users/chenzhi/MyGitlab/python-tools']
102 INFO: checking Analysis
103 INFO: Building Analysis because out00-Analysis.toc is non existent
103 INFO: Initializing module dependency graph...
104 INFO: Initializing module graph hooks...
106 INFO: Analyzing base_library.zip ...
3819 INFO: running Analysis out00-Analysis.toc
3827 INFO: Caching module hooks...
3831 INFO: Analyzing /Users/chenzhi/MyGitlab/python-tools/pyQrcode.py
3939 INFO: Processing pre-safe import module hook   six.moves
4806 INFO: Loading module hooks...
4806 INFO: Loading module hook "hook-PyQt5.py"...
4927 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
4928 INFO: Loading module hook "hook-encodings.py"...
4998 INFO: Loading module hook "hook-PIL.py"...
5000 INFO: Excluding import 'PyQt5'
5002 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
5002 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
5002 INFO: Excluding import 'PySide'
5003 INFO:   Removing import of PySide from module PIL.ImageQt
5003 INFO: Excluding import 'PyQt4'
5004 INFO:   Removing import of PyQt4 from module PIL.ImageQt
5005 INFO: Import to be excluded not found: 'tkinter'
5005 INFO: Import to be excluded not found: 'FixTk'
5005 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
5483 INFO: Loading module hook "hook-PIL.Image.py"...
5944 INFO: Processing pre-find module path hook   distutils
6051 INFO: Loading module hook "hook-PyQt5.Qt.py"...
6052 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
6052 INFO: Loading module hook "hook-xml.py"...
6333 INFO: Loading module hook "hook-pydoc.py"...
6334 INFO: Loading module hook "hook-distutils.py"...
6336 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
6417 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
6419 INFO: Excluding import 'tkinter'
6420 INFO: Import to be excluded not found: 'FixTk'
6420 INFO: Loading module hook "hook-_tkinter.py"...
6430 INFO: checking Tree
6430 INFO: Building Tree because out00-Tree.toc is non existent
6430 INFO: Building Tree out00-Tree.toc
6497 INFO: checking Tree
6497 INFO: Building Tree because out01-Tree.toc is non existent
6497 INFO: Building Tree out01-Tree.toc
6526 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
6629 INFO: Looking for ctypes DLLs
6630 INFO: Analyzing run-time hooks ...
6633 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6641 INFO: Looking for dynamic libraries
6874 INFO: Looking for eggs
6874 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.6.0/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "/usr/local/opt/pyenv/versions/3.6.0/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: Python, libpython3.6.dylib, libpython3.6m.dylib, .Python
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
```

**Comment by jenshnielsen** [comment]
Does it work if you build with framework support as suggested in the last line?
e.g. to install 3.6.0 
```
PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.0
```

Taken from the matplotlib documentation. https://matplotlib.org/faq/osx_framework.html

**Comment by newlarry** [comment]
I was having the same  problem and this did indeed work for me. Thanks.

`PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.4`

**Comment by anapaulagomes** [comment]
If you're using `pyenv`, don't forget of loading it as the local/global version and reload it afterwards (`eval "$(pyenv init -)"`. :)
