### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by joisonwk** [pyenv/pyenv#1115]
How to solve this problem, when I using the pip install any python libraries,  the error message all ways existed. Who has had the same problem?
Here are the error tips:
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2708, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==1.0
```

**Comment by chrahunt** [comment]
Hi. How is this related to pyenv? All of the paths in your traceback seem to be from your system Python.

**Comment by chrahunt** [comment]
Please create a new issue if there is something related to pyenv we can help with!
