### ISSUE TITLE
Creating virtualenv programatically within another virtualenv doesn't work with pyenv

### ISSUE THREAD

**Issue by abingham** [pyenv/pyenv#1262]
I've been trying to track down a problem creating virtual environments programatically. If I'm in a virtual environment created without pyenv, the following code works fine:
```
import venv
b = venv.EnvBuilder(with_pip=True)
b.create('name')
```
However, if I run this in a virtual environment created with a Python managed by pyenv, I get this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sixtynorth/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/venv/__init__.py", line 67, in create
    self._setup_pip(context)
  File "/Users/sixtynorth/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/venv/__init__.py", line 245, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Users/sixtynorth/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/sixtynorth/.pyenv/versions/3.6.6/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/sixtynorth/sandbox/name/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

The source of this seems to be that the virtualenv is simply not fully constructed. For example, if I look in the `bin` directory of the virtualenv `name` I only see `python` and `python3`, i.e. no activate scripts. If I try to run one of these pythons directly, I get this error:
```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/sixtynorth/sandbox/name/bin/python
  Reason: image not found
[1]    34591 abort      name/bin/python
```
The only variable that seems to correlate with this problem is whether I'm using pyenv to manage Python versions. I don't know if this is a pyenv bug per se, but at this point that's the only thing that seems to make sense.

**Comment by abingham** [comment]
Hmmm...a bit more digging seems to indicate that this isn't a pyenv issue. Sorry for the noise.

**Comment by p-i-** [comment]
It might be helpful To random Googlers if you were to say what the problem _was_.
I'm also bumping into this issue.
