### ISSUE TITLE
Custom python version does not detect libffi

### ISSUE THREAD

**Issue by narun4sk** [pyenv/pyenv#1474]
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
```
> uname -a
Linux archlinux 5.4.1-arch1-1 #1 SMP PREEMPT Fri, 29 Nov 2019 13:37:24 +0000 x86_64 GNU/Linux
```
- [x] OS architecture (e.g. amd64): `x86_64`

- [x] pyenv version:
```
> pyenv --version
pyenv 1.2.15
```
- [x] Python version:
```
> python --version
Python 3.8.0
```
- [x] C Compiler information (e.g. gcc 7.3):
```
> pacman -Q | grep gcc
gcc-libs 9.2.0-4
gcc8 8.3.0-4
gcc8-libs 8.3.0-4
lib32-gcc-libs 9.2.0-4
```
- [x] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

https://gist.github.com/narun4sk/2bfd9e1da61181d654ba28730f57028d

---

Below you can see I have installed python `3.8.0` and activated it in the current shell:
```
nrz@archlinux ~> pyenv versions
* system (set by /home/nrz/.pyenv/version)
  3.7.5
  3.8.0
nrz@archlinux ~> pyenv shell 3.8.0
nrz@archlinux ~> pyenv version
3.8.0 (set by PYENV_VERSION environment variable)
```

Next I'll try to install the package:
```
nrz@archlinux ~> pip install git+https://github.com/ducksboard/libsaas.git#egg=libsaas
Collecting libsaas from git+https://github.com/ducksboard/libsaas.git#egg=libsaas
  Cloning https://github.com/ducksboard/libsaas.git to /tmp/pip-install-1d8z3h0c/libsaas
  Running command git clone -q https://github.com/ducksboard/libsaas.git /tmp/pip-install-1d8z3h0c/libsaas
    ERROR: Command errored out with exit status 1:
     command: /home/nrz/.pyenv/versions/3.8.0/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1d8z3h0c/libsaas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1d8z3h0c/libsaas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-1d8z3h0c/libsaas/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nrz/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/nrz/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/home/nrz/.pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/nrz/.pyenv/versions/3.8.0/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

It failed, so I'll create a `virtualenv` based on my `system`'s python and activate it:
```
nrz@archlinux ~ [1]> pyenv virtualenv system sys-test
Using base prefix '/usr'
New python executable in /home/nrz/.pyenv/versions/sys-test/bin/python
Installing setuptools, pip, wheel...
done.
Looking in links: /tmp/tmp6v_6g82j
Requirement already satisfied: setuptools in /home/nrz/.pyenv/versions/sys-test/lib/python3.8/site-packages (42.0.2)
Requirement already satisfied: pip in /home/nrz/.pyenv/versions/sys-test/lib/python3.8/site-packages (19.3.1)
nrz@archlinux ~> pyenv shell sys-test 
nrz@archlinux ~> pyenv version
sys-test (set by PYENV_VERSION environment variable)
```
Now will attempt to install again:
```
nrz@archlinux ~> pip install git+https://github.com/ducksboard/libsaas.git#egg=libsaas
Collecting libsaas
  Cloning https://github.com/ducksboard/libsaas.git to /tmp/pip-install-s7g98aa_/libsaas
  Running command git clone -q https://github.com/ducksboard/libsaas.git /tmp/pip-install-s7g98aa_/libsaas
Building wheels for collected packages: libsaas
  Building wheel for libsaas (setup.py) ... done
  Created wheel for libsaas: filename=libsaas-0.4-cp38-none-any.whl size=217211 sha256=30a3b38c12d05cab0377ec1bce2e606ebb138741c205dc6bb49395a958c4decc
  Stored in directory: /tmp/pip-ephem-wheel-cache-u4g8h6kl/wheels/1f/c0/d0/0e94921f0a6f902a7056c917a8f1c9d5ce4ded8513f3ab5eee
Successfully built libsaas
Installing collected packages: libsaas
Successfully installed libsaas-0.4
```
Tada :tada: It worked this time...

`libffi` Is definitely installed on my system:
```
nrz@archlinux ~> pacman -Ql libffi
libffi /usr/
libffi /usr/lib/
libffi /usr/lib/libffi-3.2.1/
libffi /usr/lib/libffi-3.2.1/include/
libffi /usr/lib/libffi-3.2.1/include/ffi.h
libffi /usr/lib/libffi-3.2.1/include/ffitarget.h
libffi /usr/lib/libffi.so
libffi /usr/lib/libffi.so.6
libffi /usr/lib/libffi.so.6.0.4
libffi /usr/lib/pkgconfig/
libffi /usr/lib/pkgconfig/libffi.pc
libffi /usr/share/
libffi /usr/share/info/
libffi /usr/share/info/libffi.info.gz
libffi /usr/share/licenses/
libffi /usr/share/licenses/libffi/
libffi /usr/share/licenses/libffi/LICENSE
libffi /usr/share/man/
libffi /usr/share/man/man3/
libffi /usr/share/man/man3/ffi.3.gz
libffi /usr/share/man/man3/ffi_call.3.gz
libffi /usr/share/man/man3/ffi_prep_cif.3.gz
libffi /usr/share/man/man3/ffi_prep_cif_var.3.gz
```

But in the build log I can see it hasn't been detected anyway...
https://gist.github.com/narun4sk/2bfd9e1da61181d654ba28730f57028d#file-pyenv-3-8-0-log-L1177

Any ideas?

**Comment by bryantbiggs** [comment]
I'm facing same issue on fresh install of ubuntu 19.04; libffi is there but its failing to find ctypes

**Comment by jwinnie** [comment]
Same problem, Arch Linux.

You can read the details (crash log, system specifications) here: pypa/pipenv#4194.

**Comment by tybrs** [comment]
Try rebuilding python install with pyenv. Worked for me.

**Comment by jwinnie** [comment]
@tybrs That worked for me.

But I filed this issue because Pyenv shouldn't randomly crash like that. There should be some mechanism to detect a newer library version and automatically rebuild.

**Comment by JJ** [comment]
This is probably not the issue here, but I managed to fix this installing previously libffi-dev (in Ubuntu), and re-installing the Python version I was interested in. A simple documentation change indicating this would probably be enough.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/wiki/Common-build-problems#python-cannot-find-a-dependent-dynamic-library-even-though-its-installed
