### ISSUE TITLE
Installing any module gives AttributeError: '_shims' object has no attribute 'InstallRequirement'

### ISSUE THREAD

**Issue by patoski** [pyenv/pyenv#1511]
Whenever I try to install any module e.g. `pipenv install requests` I get the following error:
```
Installing requests…
Traceback (most recent call last):
  File "/home/foo/.pyenv/versions/3.8.1/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/core.py", line 1909, in do_install
    pkg_requirement = Requirement.from_line(pkg_line)
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1068, in from_line
    if isinstance(line, pip_shims.shims.InstallRequirement):
  File "/home/foo/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pipenv/vendor/pip_shims/shims.py", line 254, in __getattr__
    return super(_shims, self).__getattribute__(*args, **kwargs)
AttributeError: '_shims' object has no attribute 'InstallRequirement'
```
I've tried Python 3.8.1 and 3.7.6 without any success. I've reinstalled pyenv a number of times but can't get past this issue. Any assistance would be really appreciated!

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04):
Void Linux 5.3.18_1 x86_64 GenuineIntel uptodate rFFFFF (rolling distro fully updated)
- [X] OS architecture (e.g. amd64):
amd64
- [X] pyenv version:
pyenv 1.2.15-11-g4e0ba2f4
- [X] Python version:
3.8.1
- [X] C Compiler information (e.g. gcc 7.3):
gcc (GCC) 9.2.0
- [X] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
https://gist.github.com/patoski/b4a4310f301541981b0dd48da24e8051#file-pipenv-install-requests-txt

**Comment by native-api** [comment]
https://gist.github.com/patoski/b4a4310f301541981b0dd48da24e8051#file-pipenv-install-requests-txt-L245

Looks like your Python wasn't built correctly.
See https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites
