### ISSUE TITLE
cant use python-box with pyenv on macos

### ISSUE THREAD

**Issue by jianglijie** [pyenv/pyenv#1514]
I installed pyenv and virtualenv on my macos and I found the file "box.py" in "/usr/local/var/pyenv/shims/box.py". Open the file it shows 
```
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/usr/local/var/pyenv"
exec "/usr/local/Cellar/pyenv/1.1.5/libexec/pyenv" exec "$program" "$@"
```
I cant use python-box at the same time, error show like
```
Traceback (most recent call last):
  File "run/tools/test.py", line 7, in <module>
    from dynaconf import settings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/__init__.py", line 1, in <module>
    from dynaconf.base import LazySettings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/base.py", line 7, in <module>
    from dynaconf import default_settings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/default_settings.py", line 11, in <module>
    from dynaconf.utils.parse_conf import parse_conf_data
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/utils/parse_conf.py", line 5, in <module>
    from box import BoxKeyError
  File "/usr/local/var/pyenv/shims/box.py", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
```
It use "/usr/local/var/pyenv/shims/box.py"first not python-box

**Comment by native-api** [comment]
There should not be a "`/usr/local/var/pyenv/`", at least not in recent versions. No idea what that it.

Uninstall `pyenv`, remove that directory and anything else that resembles `pyenv` under `/usr/local` and your home directory and in your shell startup files.
Then install the latest version.
