### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by binarykitchen** [pyenv/pyenv#1520]
```
multiprocessing.pool.RemoteTraceback:
"""
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/model/package.py", line 100, in __init__
    """ % self.name)
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/db.py", line 49, in query
    cursor.execute(*args, **kwargs)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/commands/helper.py", line 310, in get_registry_from_pip
    build_dependency_tree = build_dependency_tree, jobs = jobs)
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/model/registry.py", line 105, in __init__
    for package in pool.imap_unordered(partial(Package, **args), packages):
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/bin/pipupgrade", line 8, in <module>
    sys.exit(main())
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 15, in wrapper
    return fn(**params)
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 156, in command
    pip_path
  File "/Users/michael-heuberger/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
MemoryError
```

**Comment by binarykitchen** [comment]
Command is `pipupgrade -ly --no-cache-dir --pip-path pip`

**Comment by joshfriend** [comment]
Your exception traces don't seem to have anything to do with pyenv. Please report your issue to a more appropriate project (perhaps whatever pipupgrade is?) or at least explain why you think the issue is caused by pyenv.
