### ISSUE TITLE
Python 3.8.1 - pip crashing 

### ISSUE THREAD

**Issue by brupelo** [pyenv/pyenv#1567]
Maybe related to #1304?

Please take a look to this session

```
[vagrant@localhost ~]$ sudo yum install @development zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel 
 openssl-devel xz xz-devel libffi-devel findutils                                                                    
Loaded plugins: fastestmirror                                                                                        
Loading mirror speeds from cached hostfile                                                                           
 * base: mirror.airenetworks.es                                                                                      
 * epel: mirror.neostrada.nl                                                                                         
 * extras: mirror.airenetworks.es                                                                                    
 * updates: mirror.airenetworks.es                                                                                   
Package zlib-devel-1.2.7-18.el7.x86_64 already installed and latest version                                          
Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version                                               
Package bzip2-devel-1.0.6-13.el7.x86_64 already installed and latest version                                         
Package readline-devel-6.2-11.el7.x86_64 already installed and latest version                                        
Package sqlite-3.7.17-8.el7_7.1.x86_64 already installed and latest version                                          
Package sqlite-devel-3.7.17-8.el7_7.1.x86_64 already installed and latest version                                    
Package 1:openssl-devel-1.0.2k-19.el7.x86_64 already installed and latest version                                    
Package xz-5.2.2-1.el7.x86_64 already installed and latest version                                                   
Package xz-devel-5.2.2-1.el7.x86_64 already installed and latest version                                             
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version                                       
Package 1:findutils-4.5.11-6.el7.x86_64 already installed and latest version                                         
Nothing to do                                                                                                        
[vagrant@localhost ~]$ cat /etc/centos-release                                                                       
CentOS Linux release 7.7.1908 (Core)                                                                                 
[vagrant@localhost ~]$ pyenv versions                                                                                
  system                                                                                                             
  3.6.2                                                                                                              
* 3.8.1 (set by /home/vagrant/.pyenv/version)                                                                        
  stackless-3.5.4                                                                                                    
[vagrant@localhost ~]$ pip install autopep8                                                                          
Collecting autopep8                                                                                                  
  Using cached autopep8-1.5.tar.gz (116 kB)                                                                          
    ERROR: Command errored out with exit status 1:                                                                   
     command: /home/vagrant/.pyenv/versions/3.8.1/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '
"'"'/tmp/pip-install-ogdpo4zy/autopep8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ogdpo4zy/autopep8/setup.py'"'"';
f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe
c(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ogdpo4zy/autopep8/pip-egg-info      
         cwd: /tmp/pip-install-ogdpo4zy/autopep8/                                                                    
    Complete output (11 lines):                                                                                      
    Traceback (most recent call last):                                                                               
      File "<string>", line 1, in <module>                                                                           
      File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <mod
ule>                                                                                                                 
        from setuptools.dist import Distribution, Feature                                                            
      File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
                                                                                                                     
        from setuptools import windows_support                                                                       
      File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, i
n <module>                                                                                                           
        import ctypes                                                                                                
      File "/home/vagrant/.pyenv/versions/3.8.1/lib/python3.8/ctypes/__init__.py", line 7, in <module>               
        from _ctypes import Union, Structure, Array                                                                  
    ModuleNotFoundError: No module named '_ctypes'                                                                   
    ----------------------------------------                                                                         
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.      
[vagrant@localhost ~]$ pyenv global 3.6.2
[vagrant@localhost ~]$ pip install autopep8
Collecting autopep8
  Using cached autopep8-1.5.tar.gz (116 kB)
Requirement already satisfied: pycodestyle>=2.5.0 in ./.pyenv/versions/3.6.2/lib/python3.6/site-packages (from autopep8) (2.5.0)
Installing collected packages: autopep8
    Running setup.py install for autopep8 ... done
Successfully installed autopep8-1.5
[vagrant@localhost ~]$ pyenv --version
pyenv 1.2.15-11-g4e0ba2f
```

What's wrong here and why pip it's crashing with 3.8.1 but not crashing with 3.6.2 ?

**Comment by brupelo** [comment]
Never mind, this issue is not valid... I had installed python3.8.1 with pyenv's requisites not meeting properly :/ . I guess the problem was doing `pyenv install 3.8.1` didn't report any error in the first place so I assumed everything worked ok... Is that a bug?
