### ISSUE TITLE
Pyenv on Big Sur does not install curses module

### ISSUE THREAD

**Issue by fallenstorm** [pyenv/pyenv#1755]
### ENV

- Big Sur 11.0.1 
- pyenv 1.2.21

### Description
pyenv installs any python version without common module _curses.
I installed version as it says in this bug https://github.com/pyenv/pyenv/issues/1746

```
% pyenv local 3.8.6
% python -V
Python 3.8.6
% python
Python 3.8.6 (default, Dec 11 2020, 15:28:53)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/machizhov/.pyenv/versions/3.8.6/lib/python3.8/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by aidanlister** [comment]
I'm getting the same problem.

**Comment by hopson** [comment]
I have been able to work around this by including `ncurses` in the `FLAGS`:
```
CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(brew --prefix ncurses)/include -I$(xcrun --show-sdk-path)/usr/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix ncurses)/lib -L$(xcrun --show-sdk-path)/usr/lib" \
pyenv install 3.8.6
```
Shell output:
```
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.8.6...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.8.6 to /Users/hopson/.pyenv/versions/3.8.6

❯ pyenv shell 3.8.6
❯ python
Python 3.8.6 (default, Dec 11 2020, 12:22:12)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>>
```

**Comment by aidanlister** [comment]
This is what I needed to get it working:

```export CFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix openssl)/include -I$(brew --prefix readline)/include -I$(brew --prefix ncurses)/include -I$(xcrun --show-sdk-path)/usr/include"

export LDFLAGS="-L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib -L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix ncurses)/lib -L$(xcrun --show-sdk-path)/usr/lib"
```
