### ISSUE TITLE
Cannot install python 3.8 versions on ubuntu

### ISSUE THREAD

**Issue by kyrick** [pyenv/pyenv#1803]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.04.2 LTS
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 1.2.22-47-g4c302a02
- [x] Python version: system python is 3.8.5
- [x] C Compiler information (e.g. gcc 7.3): 9.3.0
- [x] Please attach verbose build log [Verbose log](https://gist.github.com/kyrick/7dc9ae0d9202fd4cc91e26c40edfb1ca)

I can't install any python 3.8 versions. Perplexingly pyenv can install python 3.7 and 3.9 versions. My system python is 3.8 so maybe that's creating some conflict? I've verified that no other python environment variables beyond that required for pyenv. I'm not sure what else to try. The install terminates with module not found `_posixsubprocess`, which is perplexing.
```
Traceback (most recent call last):
  File "./setup.py", line 13, in <module>
    from distutils import log
  File "/home/kyrick/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 83, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/tmp/python-build.20210205105901.401161/Python-3.8.7/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/kyrick/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/kyrick/.local/lib/python3.8/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/kyrick/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 64, in do_override
    ensure_local_distutils()
  File "/home/kyrick/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py", line 51, in ensure_local_distutils
    core = importlib.import_module('distutils.core')
  File "/tmp/python-build.20210205105901.401161/Python-3.8.7/Lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/kyrick/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 16, in <module>
    from distutils.dist import Distribution
  File "/home/kyrick/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 19, in <module>
    from distutils.util import check_environ, strtobool, rfc822_escape
  File "/home/kyrick/.local/lib/python3.8/site-packages/setuptools/_distutils/util.py", line 14, in <module>
    from distutils.spawn import spawn
  File "/home/kyrick/.local/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 11, in <module>
    import subprocess
  File "/tmp/python-build.20210205105901.401161/Python-3.8.7/Lib/subprocess.py", line 69, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'
```

**Comment by native-api** [comment]
The the log, the Python beinf installed tried to use the modules of your installation in `/home/kyrick/.local/lib/python3.8`.

I guess you have messed with envvars -- e.g. `PYTHONPATH`. Unset any Python-specific envvars.

**Comment by amuletxheart** [comment]
I got this issue after upgrading from ubuntu 20.04 to 21.10, and fixed it removing the python3.8 folder.

`rm -rf ~/.local/lib/python3.8`
