### ISSUE TITLE
Unresolved? -- pyenv install doesn't work with homebrew installed tcl-tk #1375

### ISSUE THREAD

**Issue by stevenjstromer** [pyenv/pyenv#2109]
Environment:
```
OSX 10.15.7
2.3 GHz Dual-Core Intel Core i5
pyenv 2.1.0
Python 3.10.0

gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Issue (I see that the functions use_homebrew_tcltk(), use_custom_tcltk() and get_tcltk_flag_from() have been added to python-build file to attempt to address this issue, but I am experiencing it, nonetheless):
```
% idle                
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Users/sstromer/.pyenv/versions/3.10.0/bin/idle", line 5, in <module>
    main()
  File "/Users/sstromer/.pyenv/versions/3.10.0/lib/python3.10/idlelib/pyshell.py", line 1609, in main
    root = Tk(className="Idle")
  File "/Users/sstromer/.pyenv/versions/3.10.0/lib/python3.10/tkinter/__init__.py", line 2301, in __init__
    self._loadtk()
  File "/Users/sstromer/.pyenv/versions/3.10.0/lib/python3.10/tkinter/__init__.py", line 2317, in _loadtk
    raise RuntimeError("tk.h version (%s) doesn't match libtk.a version (%s)"
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```

Additional details...
```
%  tclsh <<< 'puts [info patchlevel]'
8.6.11

% vi ~/.zshrc
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
eval "$(pyenv init -)"
export PATH="/usr/local/opt/tcl-tk/bin:$PATH"

% brew --prefix tcl-tk
/usr/local/opt/tcl-tk
```

Install process was as follows:
```
% brew install tcl-tk
% echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.zshrc
% source ~/.zshrc
% export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"
% export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"
i% export PKG_CONFIG_PATH="/usr/local/opt/tcl-tk/lib/pkgconfig"
% pyenv uninstall 3.10.0
% pyenv install 3.10.0
```

Please let me know if I am missing something obvious, or if I can provide any additional info. thnx.

**Comment by native-api** [comment]
WFM.
Please provide the necessary diagnostic details as required by the issue template -- in particular, debug trace of the installation command of the faulty Python.
Looks like your Python is linking to a system instance of Tk - which should not be happening.

**Comment by native-api** [comment]
Also please show the outpu of `otool -L /Users/sstromer/.pyenv/versions/3.10.0//lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so`

**Comment by native-api** [comment]
> /Users/sstromer/.pyenv/versions/3.10.0/lib/python3.10/lib-dynload/_tkinter.cpython-310-darwin.so:
> 	/usr/local/opt/tcl-tk/lib/libtcl8.6.dylib (compatibility version 8.6.0, current version 8.6.11)
> 	/usr/local/opt/tcl-tk/lib/libtk8.6.dylib (compatibility version 8.6.0, current version 8.6.11)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)

That is correct. It should load these libraries.
Do you have any envvars that affect MacOS' dynamic linker?

**Comment by stevenjstromer** [comment]
native-api,

Success, after many attempts. I uninstalled not only Python, but also pyenv, and removed all entries in .zshrc, then restarted the shell, and reinstalled everything. I believe that inadvertently using outdated installation instructions pulled off the web for pyenv had me setting a path to the OSX instance of tcl-tk in .zshrc, which likely affected the install of pyenv. Sorry for inconveniencing you, but it is such a joy to finally have a working environment. Your responsiveness has been extremely encouraging. Be well!
