### ISSUE TITLE
ModuleNotFoundError: No module named `_bz2`

### ISSUE THREAD

**Issue by Harmouch101** [pyenv/pyenv#2265]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Ubuntu 20.04.4 LTS.
- [x] OS architecture: amd64.
- [x] pyenv version:

```sh
(.venv) ➜  ✗ pyenv --version
pyenv 2.2.4-1-4-g1e79a522
```

- [x] Python version:

```sh
(.venv) ➜  ✗ python3 --version
Python 3.8.10
```

- [x] C Compiler information:

```sh
(.venv) ➜  ✗ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```
 
- [x] Please attach the debug trace of the failing command:

```
(.venv) ➜  ✗ python3 -c "import bz2;" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/harmouch/.pyenv/versions/3.8.10/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by Harmouch101** [comment]
I have reinstalled this specific python version,  and it seems to be working. Not sure what went wrong. That's odd!

**Comment by Harmouch101** [comment]
Hey @native-api, I have a question regarding the `attr` module, was it removed from python 3.9? Because when importing it using python 3.8.10, it seems to be working. However, it is not the case with 3.9.10:

```bash
(.venv) ➜  python3 -c "import attr;"    
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'attr'
```

I searched in the log, but it seems to be removed as of python 3.9.
in 3.8.10, the following line mentions the attr module, unlike 3.9.10:

```bash
Listing '/home/harmouch/.pyenv/versions/3.8.10/lib/python3.8/site-packages/attr'...
```
