### ISSUE TITLE
import _ssl           ModuleNotFoundError: No module named '_ssl: "libssl.so.1.1: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by vivekptl9** [pyenv/pyenv#2693]
Please help me resolve this issue. I am trying to work on it since days now. 
I am using Arch Linux distribution (Garuda linux). 
I want to install python 3.10.6 using pyenv. 
I downloaded the openssl and other prerequisites  as mentioned in pyenv documentation. I get the following error:

```
`Downloading Python-3.10.6.tar.xz...
-> https://www.python.org/ftp/python/3.10.6/Python-3.10.6.tar.xz
Installing Python-3.10.6...
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/lepton/.pyenv/versions/3.10.6/lib/python3.10/ssl.py", line 99, in <module>
import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Garuda Soaring using python-build 2.3.17-9-g528d10e9)

Inspect or clean up the working tree at /tmp/python-build.20230502111106.1217542
Results logged to /tmp/python-build.20230502111106.1217542.log

Last 10 log lines:
install|*) ensurepip="" ;; \
esac; \
LD_LIBRARY_PATH=/tmp/python-build.20230502111106.1217542/Python-3.10.6 ./python -E -m ensurepip \
$ensurepip --root=/ ; \
fi
Looking in links: /tmp/tmpc6q9pvj7
Processing /tmp/tmpc6q9pvj7/setuptools-63.2.0-py3-none-any.whl
Processing /tmp/tmpc6q9pvj7/pip-22.2.1-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-22.2.1 setuptools-63.2.0
pyenv: version `Anaemia_Classification' is not installed (set by /home/lepton/.python-version)`
```

I went in the github link where they show you common build problems and I tried using the LD flags command for the Arch linux. 
```
LDFLAGS="-L/usr/lib/openssl-3.1.0" \ # Version of openssl on my PC
CPPFLAGS="-I/usr/include/openssl-3.1.0" \
pyenv install -v 3.10.6
```
But still get the same error. 

Can you please tell what mistake I am making. For the reference I am attaching the log file.
[python-build.20230502112141.1293062.log](https://github.com/pyenv/pyenv/files/11371800/python-build.20230502112141.1293062.log)

Thank you in advance.

**Comment by native-api** [comment]
```
*** WARNING: renaming "_ssl" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory
*** WARNING: renaming "_hashlib" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Check if you have invalid links named `libssl.so` on your system pointing to a nonexistent "`libssl.so.1.1`".

**Comment by native-api** [comment]
```
*** WARNING: renaming "_ssl" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory
*** WARNING: renaming "_hashlib" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Check if you have invalid symlinks named `libssl.so` on your system pointing to a nonexistent "`libssl.so.1.1`".

You have OpenSSL 3 installed but the build tries to link against OpenSSL 1.1. The above can be the cause.

If one is in `/usr/lib`, fix it to point to the corresponding OpenSSL 3 file.
If it's in `/usr/local/lib`, delete it (this most likely means you have lefovers from a source installation of OpenSSL 1.1).
