### ISSUE TITLE
installing Python 3.11 on Debian: BUILD FAILED

### ISSUE THREAD

**Issue by SCBuergel** [pyenv/pyenv#2740]
I installed pyenv as per the instructions on an up to date blank Debian (I'm using QubesOS so it's a clean install that only was followed by an installation of `buildessentials`) and then trying to install python 3.11 but it failed:
```
$ pyenv install 3.11
Downloading Python-3.11.4.tar.xz...
-> https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz
Installing Python-3.11.4...

BUILD FAILED (Debian 11 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20230708124148.1816
Results logged to /tmp/python-build.20230708124148.1816.log

Last 10 log lines:
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20230708124148.1816/Python-3.11.4/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp1fuujxo6/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmp1fuujxo6/pip-23.1.2-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp1fuujxo6\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1862: install] Error 1
```

last lines from the respective log file:
```
changing mode of /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/_ctypes_test.cpython-311-x86_64-linux-gnu.so to 755
changing mode of /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/_codecs_hk.cpython-311-x86_64-linux-gnu.so to 755
changing mode of /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/_bisect.cpython-311-x86_64-linux-gnu.so to 755
changing mode of /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/ to 755
changing mode of /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/__pycache__ to 755
running install_scripts
copying build/scripts-3.11/2to3-3.11 -> /home/user/.pyenv/versions/3.11.4/bin
copying build/scripts-3.11/pydoc3.11 -> /home/user/.pyenv/versions/3.11.4/bin
copying build/scripts-3.11/idle3.11 -> /home/user/.pyenv/versions/3.11.4/bin
changing mode of /home/user/.pyenv/versions/3.11.4/bin/2to3-3.11 to 755
changing mode of /home/user/.pyenv/versions/3.11.4/bin/pydoc3.11 to 755
changing mode of /home/user/.pyenv/versions/3.11.4/bin/idle3.11 to 755
rm /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/_sysconfigdata__linux_x86_64-linux-gnu.py
rm -r /home/user/.pyenv/versions/3.11.4/lib/python3.11/lib-dynload/__pycache__
Creating directory /home/user/.pyenv/versions/3.11.4/share/man
Creating directory /home/user/.pyenv/versions/3.11.4/share/man/man1
/usr/bin/install -c -m 644 ./Misc/python.man \
	/home/user/.pyenv/versions/3.11.4/share/man/man1/python3.11.1
if test ! -d /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; then \
	echo "Creating directory /home/user/.pyenv/versions/3.11.4/lib/pkgconfig"; \
	/usr/bin/install -c -d -m 755 /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; \
fi
if test -f /home/user/.pyenv/versions/3.11.4/bin/python3 -o -h /home/user/.pyenv/versions/3.11.4/bin/python3; \
then rm -f /home/user/.pyenv/versions/3.11.4/bin/python3; \
else true; \
fi
(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s python3.11 python3)
if test "3.11" != "3.11"; then \
	rm -f /home/user/.pyenv/versions/3.11.4/bin/python3.11-config; \
	(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s python3.11-config python3.11-config); \
	rm -f /home/user/.pyenv/versions/3.11.4/lib/pkgconfig/python-3.11.pc; \
	(cd /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; ln -s python-3.11.pc python-3.11.pc); \
	rm -f /home/user/.pyenv/versions/3.11.4/lib/pkgconfig/python-3.11-embed.pc; \
	(cd /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; ln -s python-3.11-embed.pc python-3.11-embed.pc); \
fi
rm -f /home/user/.pyenv/versions/3.11.4/bin/python3-config
(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s python3.11-config python3-config)
rm -f /home/user/.pyenv/versions/3.11.4/lib/pkgconfig/python3.pc
(cd /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; ln -s python-3.11.pc python3.pc)
rm -f /home/user/.pyenv/versions/3.11.4/lib/pkgconfig/python3-embed.pc
(cd /home/user/.pyenv/versions/3.11.4/lib/pkgconfig; ln -s python-3.11-embed.pc python3-embed.pc)
rm -f /home/user/.pyenv/versions/3.11.4/bin/idle3
(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s idle3.11 idle3)
rm -f /home/user/.pyenv/versions/3.11.4/bin/pydoc3
(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s pydoc3.11 pydoc3)
rm -f /home/user/.pyenv/versions/3.11.4/bin/2to3
(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s 2to3-3.11 2to3)
if test "x" != "x" ; then \
	rm -f /home/user/.pyenv/versions/3.11.4/bin/python3-32; \
	(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s python3.11-32 python3-32) \
fi
if test "x" != "x" ; then \
	rm -f /home/user/.pyenv/versions/3.11.4/bin/python3-intel64; \
	(cd /home/user/.pyenv/versions/3.11.4/bin; ln -s python3.11-intel64 python3-intel64) \
fi
rm -f /home/user/.pyenv/versions/3.11.4/share/man/man1/python3.1
(cd /home/user/.pyenv/versions/3.11.4/share/man/man1; ln -s python3.11.1 python3.1)
if test "xupgrade" != "xno"  ; then \
	case upgrade in \
		upgrade) ensurepip="--upgrade" ;; \
		install|*) ensurepip="" ;; \
	esac; \
	LD_LIBRARY_PATH=/tmp/python-build.20230708124148.1816/Python-3.11.4 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
Traceback (most recent call last):
  File "<frozen zipimport>", line 576, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 624, in _get_data
  File "<frozen zipimport>", line 579, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<frozen runpy>", line 222, in run_module
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "<frozen zipimport>", line 195, in get_code
  File "<frozen zipimport>", line 758, in _get_module_code
  File "<frozen zipimport>", line 626, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/python-build.20230708124148.1816/Python-3.11.4/Lib/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20230708124148.1816/Python-3.11.4/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp1fuujxo6/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmp1fuujxo6/pip-23.1.2-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp1fuujxo6\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1862: install] Error 1
```

**Comment by native-api** [comment]
> zipimport.ZipImportError: can't decompress data; zlib not available

Install Python build prerequisites [as per the README](https://github.com/pyenv/pyenv#install-python-build-dependencies).

**Comment by SCBuergel** [comment]
that fixed it - thx!

**Comment by Matheus-Pedro** [comment]
For people with this problem, just read the documentation: https://github.com/pyenv/pyenv/wiki/Common-build-problems

**Comment by muggledy** [comment]
For the problem, i execute below commands:
```shell
sudo apt-get install libbz2-dev libffi-dev libncurses-dev libreadline-dev libssl-dev zlib1g-dev
sudo apt-get install libsqlite3-dev libdb-dev libgdbm-dev liblzma-dev tk-dev uuid-dev
```
Then make install again, success!
Reference: https://stackoverflow.com/questions/77534122/modulenotfounderror-no-module-named-zlib-python3-12-0-install-failed
