### ISSUE TITLE
Error installing GraalPy 23.1.0 on Linux

### ISSUE THREAD

**Issue by gwerbin** [pyenv/pyenv#2854]
Am I missing a dependency? I tried to search the Wiki, Readme, past issues, Stackoverflow, and discussion in related PRs.

<details>
<summary>JVM stack trace</summary>

```none
ERROR: java.lang.UnsupportedOperationException: Could not load posix support library from path '/home/mg/.local/opt/pyenv/versions/graalpy-community-23.1.0/lib/graalpy23.1/libposix.so'. Troubleshooting: 
Check permissions of the file.
Missing runtime Maven dependency 'org.graalvm.truffle:truffle-nfi-libffi' (should be a dependency of `org.graalvm.polyglot:python{-community}`)?
org.graalvm.polyglot.PolyglotException: java.lang.UnsupportedOperationException: Could not load posix support library from path '/home/mg/.local/opt/pyenv/versions/graalpy-community-23.1.0/lib/graalpy23.1/libposix.so'. Troubleshooting: 
Check permissions of the file.
Missing runtime Maven dependency 'org.graalvm.truffle:truffle-nfi-libffi' (should be a dependency of `org.graalvm.polyglot:python{-community}`)?
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.loadLibrary(NFIPosixSupport.java:371)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.call(NFIPosixSupport.java:305)
	at com.oracle.graal.python.runtime.NFIPosixSupport$InvokeNativeFunction.callLong(NFIPosixSupport.java:320)
	at com.oracle.graal.python.runtime.NFIPosixSupport.lseek(NFIPosixSupport.java:617)
	at com.oracle.graal.python.runtime.NFIPosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(NFIPosixSupportGen.java:6097)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupport.lseek(ImageBuildtimePosixSupport.java:258)
	at com.oracle.graal.python.runtime.ImageBuildtimePosixSupportGen$PosixSupportLibraryExports$Uncached.lseek(ImageBuildtimePosixSupportGen.java:2330)
	at com.oracle.graal.python.runtime.PosixSupportLibraryGen$UncachedDispatch.lseek(PosixSupportLibraryGen.java:6808)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$SeekNode.internalSeek(FileIOBuiltins.java:813)
	at com.oracle.graal.python.builtins.modules.io.FileIOBuiltins$TellNode.internalTell(FileIOBuiltins.java:838)
	at com.oracle.graal.python.builtins.modules.io.AbstractBufferedIOBuiltins$BufferedInitNode.internalInit(AbstractBufferedIOBuiltins.java:120)
	at com.oracle.graal.python.builtins.modules.io.BufferedReaderBuiltins$BufferedReaderInit.internalInit(BufferedReaderBuiltins.java:103)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.initStd(SysModuleBuiltins.java:724)
	at com.oracle.graal.python.builtins.modules.SysModuleBuiltins.postInitialize(SysModuleBuiltins.java:708)
	at com.oracle.graal.python.builtins.Python3Core.postInitialize(Python3Core.java:962)
	at com.oracle.graal.python.runtime.PythonContext.patch(PythonContext.java:1458)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:404)
	at com.oracle.graal.python.PythonLanguage.patchContext(PythonLanguage.java:134)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.patchEnvContext(LanguageAccessor.java:431)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.patch(PolyglotLanguageContext.java:893)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.patch(PolyglotContextImpl.java:3500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.loadPreinitializedContext(PolyglotEngineImpl.java:1909)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1789)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:152)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context$Builder.build(Context.java:1937)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:694)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
	Suppressed: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

</details>

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
* [x] Make sure your problem is not derived from plugins.

### Description
- [x] Platform information: EndeavourOS (6.1.63-1-lts kernel)
- [x] OS architecture: Intel x86-64
- [x] pyenv version: 2.3.33
- [x] Python version: N/A
- [x] C Compiler information: GCC 13.2.1
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/gwerbin/c240d941db65c09cb570ae36327c66dc
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory: N/A, not CPython
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach

**Comment by lvwvm** [comment]
I am receiving something related to this. But the issue seems to be regarding TLS and resources not being found.

https://gist.github.com/lvwvm/030b3fbae20d9000fbba986bd751909d

**Comment by native-api** [comment]
@lvwvm your problem is unrelated to this ticket or Pyenv. Your `aria2c` cannot verify Github's TLS certificate.
