### ISSUE TITLE
Installing Pyenv on Ubuntu 20.04 (Azure ML instance) fails

### ISSUE THREAD

**Issue by houmie** [pyenv/pyenv#2931]
Installing Pyenv on Ubuntu 20.04 (Azure ML instance) fails.

```
azureuser@llm2:~$ pyenv install 3.11.7
Downloading Python-3.11.7.tar.xz...
-> https://www.python.org/ftp/python/3.11.7/Python-3.11.7.tar.xz
Installing Python-3.11.7...

BUILD FAILED (Ubuntu 20.04 using python-build 2.3.35)

Inspect or clean up the working tree at /tmp/python-build.20240320083247.62471
Results logged to /tmp/python-build.20240320083247.62471.log

Last 10 log lines:
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/tmp/python-build.20240320083247.62471/Python-3.11.7/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/tmp/python-build.20240320083247.62471/Python-3.11.7/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [Makefile:1871: install] Error 1
```

### Description
- [ ] Platform information: Ubuntu 20.04
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: Latest
- [ ] Python version: 3.11.7
- [ ] C Compiler information : gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0 

```
Creating directory /home/azureuser/.pyenv/versions/3.11.7/share/man/man1
/usr/bin/install -c -m 644 ./Misc/python.man \
        /home/azureuser/.pyenv/versions/3.11.7/share/man/man1/python3.11.1
if test ! -d /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; then \
        echo "Creating directory /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig"; \
        /usr/bin/install -c -d -m 755 /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; \
fi
if test -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3 -o -h /home/azureuser/.pyenv/versions/3.11.7/bin/python3; \
then rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3; \
else true; \
fi
(cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s python3.11 python3)
if test "3.11" != "3.11"; then \
        rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3.11-config; \
        (cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s python3.11-config python3.11-config); \
        rm -f /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig/python-3.11.pc; \
        (cd /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; ln -s python-3.11.pc python-3.11.pc); \
        rm -f /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig/python-3.11-embed.pc; \
        (cd /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; ln -s python-3.11-embed.pc python-3.11-embed.pc); \
fi
rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3-config
(cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s python3.11-config python3-config)
rm -f /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig/python3.pc
(cd /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; ln -s python-3.11.pc python3.pc)
rm -f /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig/python3-embed.pc
(cd /home/azureuser/.pyenv/versions/3.11.7/lib/pkgconfig; ln -s python-3.11-embed.pc python3-embed.pc)
rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/idle3
(cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s idle3.11 idle3)
rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/pydoc3
(cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s pydoc3.11 pydoc3)
rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/2to3
(cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s 2to3-3.11 2to3)
if test "x" != "x" ; then \
        rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3-32; \
        (cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s python3.11-32 python3-32) \
fi
if test "x" != "x" ; then \
        rm -f /home/azureuser/.pyenv/versions/3.11.7/bin/python3-intel64; \
        (cd /home/azureuser/.pyenv/versions/3.11.7/bin; ln -s python3.11-intel64 python3-intel64) \
fi
rm -f /home/azureuser/.pyenv/versions/3.11.7/share/man/man1/python3.1
(cd /home/azureuser/.pyenv/versions/3.11.7/share/man/man1; ln -s python3.11.1 python3.1)
if test "xupgrade" != "xno"  ; then \
        case upgrade in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
        LD_LIBRARY_PATH=/tmp/python-build.20240320083247.62471/Python-3.11.7:/anaconda/envs/azureml_py38/lib/:/anaconda/envs/azureml_py38/lib/:/anaconda/envs/azureml_py38/lib/:/anaconda/envs/azureml_py38/lib/ ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/tmp/python-build.20240320083247.62471/Python-3.11.7/Lib/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/tmp/python-build.20240320083247.62471/Python-3.11.7/Lib/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
make: *** [Makefile:1871: install] Error 1
```

**Comment by CloudHunterTHEreal** [comment]
Same trouble. Pyenv installed via Homebrew
Wrong attempts for 3.12 / 3.10

**Comment by CloudHunterTHEreal** [comment]
After removing Homebrew and installing Pyenv directly, the problem went away 
- Python 3.10 and 3.12 were installed correctly.
