### ISSUE TITLE
pyenv install not working properly on Linux Mint 21.1

### ISSUE THREAD

**Issue by dnessett** [pyenv/pyenv#3071]
### Discussed in https://github.com/orgs/pyenv/discussions/3070

<div type='discussions-op-text'>

<sup>Originally posted by **dnessett** September 23, 2024</sup>
I think there may be a bug in pyenv. When I execute pyenv on a Linux Mint 21.1 machine, I get the following warnings.

```
nessett@MOLS-H-05:~/PythonProjects/HelloWorld$ pyenv install 3.10.15
Downloading Python-3.10.15.tar.xz...
-> https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tar.xz
Installing Python-3.10.15...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dnessett/.pyenv/versions/3.10.15/lib/python3.10/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
WARNING: The Python lzma extension was not compiled. Missing the lzma lib?
Installed Python-3.10.15 to /home/dnessett/.pyenv/versions/3.10.15
```
Prior to this when installing 3.10.15, I got a fatal error that openssl lib was missing. I then fixed it by:

sudo apt-get install libssl-dev

<added later> I also got a fatal error that said _ctypes were missing. I fixed that by executing:

sudo apt-get install libffi-dev
</div>

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv?tab=readme-ov-file#install-python-build-dependencies

**Comment by dnessett** [comment]
> https://github.com/pyenv/pyenv?tab=readme-ov-file#install-python-build-dependencies

Thank you. That solved the problem.
