### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by RobertAudi** [pyenv/pyenv#35]
I installed pyenv successfully using homebrew, but when I tried to install a python, I got a whole bunch of errors, but looking at the logs only one error stood out: Permission denied.

I think it's because on OS X the default install dir is set to `/lib/python2.7/site-packages/`...

So how do I change the install dir of new pythons and what do I change it to please?

**Comment by ndawe** [comment]
I've hit the same problem, only I don't have ``~/.pydistutils.cfg``. setuptools fails to install due to an empty PYTHONPATH (pyenv install 2.7.9 on Ubuntu 14.10). My workaround is to manually set PYTHONPATH in python-build and create the site-packages directory. Is there (or can there be) some way to disable installing setuptools and pip?

**Comment by mnemonicflow** [comment]
Had the same problem because I've set PYTHONPATH in ~/.profile to export PYTHONPATH="/usr/lib/python3/dist-packages/:$PYTHONPATH"

```
Exception:
Traceback (most recent call last):
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/__pycache__/six.cpython-35.pyc' -> '/tmp/pip-k2rz5tn0-uninstall/usr/lib/python3/dist-packages/__pycache__/six.cpython-35.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/req/req_install.py", line 752, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/home/alpha/.pyenv/versions/3.5.1/lib/python3.5/shutil.py", line 553, in move
    os.unlink(src)                                                                                                                                                                                                                                                             
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/__pycache__/six.cpython-35.pyc' 
```

After unsetting the PYTHONPATH the installation worked correctly, i.e. it installed the package into ./.pyenv/versions/3.5.1/lib/python3.5/site-packages
