### ISSUE TITLE
Building wxPython Phoenix using pyenv loads system library, not module library.

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [pyenv/pyenv#691]
Building wxPython Phoenix ( https://wiki.wxpython.org/ProjectPhoenix ) using the pyenv environment leads to the wrong library being loaded on module import:

```
MichaelZFreeman@linux-freeman-G41MT-S2PT ~
$ python
Python 3.5.1 (default, Sep  3 2016, 13:09:54)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michaelzfreeman/.pyenv/versions/3.5.1/lib/python3.5/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/michaelzfreeman/.pyenv/versions/3.5.1/lib/python3.5/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/michaelzfreeman/.pyenv/versions/3.5.1/lib/python3.5/site-packages/wx/_core.cpython-35m-x86_64-linux-gnu.so: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk2u_core-3.0.so.0 with link time reference
>>>

MichaelZFreeman@linux-freeman-G41MT-S2PT ~/ReturnToTheSource/Phoenix
$ ldd /home/michaelzfreeman/Downloads/blender-2.77-a5261e0-linux-glibc219-x86_64/2.77/python/lib/python3.5/site-packages/wx/_core.cpython-35m-x86_64-linux-gnu.so
    linux-vdso.so.1 =>  (0x00007ffc1892c000)
    ***libwx_gtk2u_core-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0 (0x00007fcbbdaed000)***
    libwx_baseu_net-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_baseu_net-3.0.so.0 (0x00007fcbbd8a1000)
    libwx_baseu-3.0.so.0 => /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 (0x00007fcbbd40e000)
    libpython3.5m.so.1.0 => /home/michaelzfreeman/.pyenv/versions/3.5.1/lib/libpython3.5m.so.1.0 (0x00007fcbbcef6000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcbbcb74000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcbbc86a000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcbbc654000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcbbc28b000)
    libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fcbbbc3f000)
    libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007fcbbb98a000)
    libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fcbbb77d000)
    libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fcbbb468000)
    libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fcbbb246000)
    libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fcbbaffa000)
    libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fcbbada6000)
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fcbbaa95000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fcbba75b000)
    libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fcbba554000)
    libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fcbba34c000)
    libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fcbba11a000)
    libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fcbb9ec0000)
    libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fcbb9c4d000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcbb9a30000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcbb9815000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcbb9611000)
    /lib64/ld-linux-x86-64.so.2 (0x000055d56b29f000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fcbb940d000)
    libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fcbb9209000)
    libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fcbb9002000)
    libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fcbb8ddd000)
    libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fcbb8a55000)
    libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fcbb883f000)
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fcbb85fb000)
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fcbb83f1000)
    libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fcbb81ed000)
    libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fcbb7fdd000)
    libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fcbb7dd2000)
    libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fcbb7bc8000)
    libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fcbb79c4000)
    libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fcbb77c1000)
    libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fcbb75af000)
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fcbb7304000)
    libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fcbb705c000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fcbb6e36000)
    libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fcbb6c32000)
    libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fcbb6a28000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fcbb6805000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fcbb65fd000)
    libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fcbb63f3000)
    libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fcbb61eb000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fcbb5f7b000)
    libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fcbb5d60000)
    libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fcbb5b5b000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fcbb5939000)
    libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fcbb572a000)
    libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fcbb5508000)
    libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fcbb52ec000)
    libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fcbb508e000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fcbb4e65000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fcbb4c60000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fcbb4a5a000)
    libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fcbb4851000)
    libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fcbb462c000)
```

Building in a non pyenv python (Python 3.5.1 built from source and installed to system as a Ubuntu/Debian "alternative") clears the error (actually I get a different error for an unspecified reason but that obviously has nothing to do with pyenv now).

Here is the ldd output now Phoenix has been built outside of pyenv ...

```
MichaelZFreeman@linux-freeman-G41MT-S2PT ~
$ ldd /opt/python3.5.1/lib/python3.5/site-packages/wx/_core.cpython-35m-x86_64-linux-gnu.so
    linux-vdso.so.1 =>  (0x00007ffc7becf000)
    ***libwx_gtk2u_core-3.0.so.0 => /opt/python3.5.1/lib/python3.5/site-packages/wx/libwx_gtk2u_core-3.0.so.0 (0x00007fa9b3180000)***
    libwx_baseu_net-3.0.so.0 => /opt/python3.5.1/lib/python3.5/site-packages/wx/libwx_baseu_net-3.0.so.0 (0x00007fa9b2f31000)
    libwx_baseu-3.0.so.0 => /opt/python3.5.1/lib/python3.5/site-packages/wx/libwx_baseu-3.0.so.0 (0x00007fa9b2a8f000)
    libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fa9b24d6000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa9b2154000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9b1e4a000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa9b1c34000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9b186b000)
    libgtk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007fa9b121f000)
    libgdk-x11-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007fa9b0f6a000)
    libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fa9b0d5d000)
    libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fa9b0a48000)
    libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fa9b0826000)
    libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fa9b05da000)
    libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fa9b0386000)
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa9b0075000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa9afd3b000)
    libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fa9afb34000)
    libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fa9af92c000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fa9af707000)
    libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fa9af4ad000)
    libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fa9af23a000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9af01d000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa9aee02000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa9aebfe000)
    /lib64/ld-linux-x86-64.so.2 (0x000055f484122000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa9ae9fa000)
    libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fa9ae7f6000)
    libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fa9ae5ef000)
    libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fa9ae3ca000)
    libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fa9ae042000)
    libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fa9ade2c000)
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fa9adbe8000)
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fa9ad9de000)
    libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fa9ad7da000)
    libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fa9ad5ca000)
    libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fa9ad3bf000)
    libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fa9ad1b5000)
    libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fa9acfb1000)
    libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fa9acdae000)
    libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa9acb9c000)
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa9ac8f1000)
    libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fa9ac649000)
    libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fa9ac444000)
    libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fa9ac23a000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa9ac018000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa9abe0f000)
    libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007fa9abc06000)
    libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fa9ab9fd000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa9ab78d000)
    libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fa9ab573000)
    libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa9ab36d000)
    liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa9ab14b000)
    libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007fa9aaf3d000)
    libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fa9aad1a000)
    libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa9aaaff000)
    libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fa9aa8a0000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa9aa677000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa9aa472000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa9aa26c000)
    libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fa9aa064000)
    libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fa9a9e3e000)
```

wxPython list thread: https://groups.google.com/d/msg/wxpython-dev/Xu5QHBqMEc4/U1WIo8IzDwAJ
##

**Comment by wwitzke** [comment]
I am experiencing exactly this same issue. I am using pyenv 1.1.3 on Ubuntu 16.04. Here are the commands I run to set up the environment, and the resulting output:

```
username@host:~/test$ PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.2
Downloading Python-3.6.2.tar.xz...
-> https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz
Installing Python-3.6.2...
Installed Python-3.6.2 to /home/username/.pyenv/versions/3.6.2

username@host:~/test$ pyenv local 3.6.2
username@host:~/test$ pip install wxpython
Collecting wxpython
  Downloading wxPython-4.0.0b1.tar.gz (50.6MB)
    100% |████████████████████████████████| 50.6MB 42kB/s 
Collecting six (from wxpython)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, wxpython
  Running setup.py install for wxpython ... done
Successfully installed six-1.10.0 wxpython-4.0.0b1
username@host:~/test$ python
Python 3.6.2 (default, Aug  4 2017, 12:54:04) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.pyenv/versions/3.6.2/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/username/.pyenv/versions/3.6.2/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/username/.pyenv/versions/3.6.2/lib/python3.6/site-packages/wx/_core.cpython-36m-x86_64-linux-gnu.so: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk2u_core-3.0.so.0 with link time reference
>>> 
```

"--enable-shared" is required to get wxPython to compile.

**Comment by davidroeca** [comment]
@wwitzke came across the same issue, and found that it's actually in the management of the variable `$LD_LIBRARY_PATH`.
```bash
$ python
>>> import wx
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/src/myproject/venv/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/user/src/myprojectvenv/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libwx_gtk2u_core-3.0.so.0: cannot open shared object file: No such file or directory
>>> 
```

It's solved by doing the following:

```bash
$ LD_LIBRARY_PATH=venv/lib/python3.6/site-packages/wx python
>>> import wx
>>>
```

**Comment by wwitzke** [comment]
This fixes the problem for me. Thanks!

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv/commit/eeb69b1b79c96d250761fcc72460dcccfc1173b7
