### ISSUE TITLE
Python 3.7-dev build fails if pyenv is started from sh instead of bash

### ISSUE THREAD

**Issue by brechtm** [pyenv/pyenv#767]
```bash
/ # pyenv install 3.7-dev
sha256sum: the --quiet option is meaningful only when verifying checksums
Try 'sha256sum --help' for more information.
Cloning https://hg.python.org/cpython...
Installing Python-3.7-dev...

BUILD FAILED (Alpine Linux 3.4.3 using python-build 20160602)

Inspect or clean up the working tree at /tmp/python-build.20161125113636.60
Results logged to /tmp/python-build.20161125113636.60.log

Last 10 log lines:
gcc -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers   -I. -I./Include -I/root/.pyenv/versions/3.7-dev/include  -I/root/.pyenv/versions/3.7-dev/include   -DPy_BUILD_CORE -o Parser/printgrammar.o Parser/printgrammar.c
Traceback (most recent call last):
  File "./Tools/scripts/generate_opcode_h.py", line 56, in <module>
    main(sys.argv[1], sys.argv[2])
  File "./Tools/scripts/generate_opcode_h.py", line 40, in main
    with tokenize.open(opcode_py) as fp:
AttributeError: 'module' object has no attribute 'open'
Makefile:833: recipe for target 'Include/opcode.h' failed
make: *** [Include/opcode.h] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by brechtm** [comment]
I'm having this problem when building a Docker image. This is probably due to the fact that the `$(pyenv init -)` has not been run when running pyenv from `sh`.
