### ISSUE TITLE
python 3.5.0: undefined symbol: _PyThreadState_UncheckedGet

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyenv/pyenv#989]
I am seeing this new issue since recently, on python 3.5.0 (via pyenv).

Does that ring any bells? The same tests on py 3.4.0 and py 3.6.0 work.

```
==> wheezy32: Traceback (most recent call last):
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
==> wheezy32:     return self._path2confmods[path]
==> wheezy32: KeyError: local('/vagrant/borg/borg')
==> wheezy32: 
==> wheezy32: During handling of the above exception, another exception occurred:
==> wheezy32: Traceback (most recent call last):
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
==> wheezy32:     return self._conftestpath2mod[conftestpath]
==> wheezy32: KeyError: local('/vagrant/borg/borg/conftest.py')
==> wheezy32: 
==> wheezy32: During handling of the above exception, another exception occurred:
==> wheezy32: Traceback (most recent call last):
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
==> wheezy32:     mod = conftestpath.pyimport()
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/py/_path/local.py", line 662, in pyimport
==> wheezy32:     __import__(modname)
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
==> wheezy32:     py.builtin.exec_(co, mod.__dict__)
==> wheezy32:   File "/vagrant/borg/borg/conftest.py", line 18, in <module>
==> wheezy32:     import borg.cache
==> wheezy32:   File "/vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/borg/cache.py", line 16, in <module>
==> wheezy32:     from .hashindex import ChunkIndex, ChunkIndexEntry, CacheSynchronizer
==> wheezy32: ImportError: /vagrant/borg/borg/.tox/py35/lib/python3.5/site-packages/borg/hashindex.cpython-35m-i386-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
==> wheezy32: ERROR: could not load /vagrant/borg/borg/conftest.py
```

Not sure it is a pyenv or python compilation issue, just thought I ask here in case it is.

**Comment by ThomasWaldmann** [comment]
Maybe this is due to a change in Cython, it now generates code (.pyx -> .c) like this:
```
#if !CYTHON_FAST_THREAD_STATE || PY_VERSION_HEX < 0x02070000
  #define __Pyx_PyThreadState_Current PyThreadState_GET()
#elif PY_VERSION_HEX >= 0x03050200
  #define __Pyx_PyThreadState_Current _PyThreadState_UncheckedGet()
#elif PY_VERSION_HEX >= 0x03000000
  #define __Pyx_PyThreadState_Current PyThreadState_Get()
#else
  #define __Pyx_PyThreadState_Current _PyThreadState_Current
#endif
```

**Comment by ThomasWaldmann** [comment]
It's a Cython issue:

https://github.com/cython/cython/issues/1880

Workaround: Cython!=0.27
